### ISSUE TITLE
 java.lang.IllegalArgumentException at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:595)

### ISSUE THREAD

**Issue by Pooh3Mobi** [Pooh3Mobi/Kotlin-FrpStudy#3]
```vim
03-24 17:01:15.834 23926-23926/mobi.pooh3.frpstudy W/System.err: java.lang.IllegalArgumentException
03-24 17:01:15.835 23926-23926/mobi.pooh3.frpstudy W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:595)
03-24 17:01:15.835 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.schedulers.NewThreadWorker.schedulePeriodicallyDirect(NewThreadWorker.java:91)
03-24 17:01:15.835 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.schedulers.ComputationScheduler.schedulePeriodicallyDirect(ComputationScheduler.java:139)
03-24 17:01:15.835 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.operators.observable.ObservableInterval.subscribeActual(ObservableInterval.java:41)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.operators.observable.ObservableWithLatestFrom.subscribeActual(ObservableWithLatestFrom.java:45)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:126)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:489)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:450)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:154)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.operators.observable.ObservableSwitchMap.subscribeActual(ObservableSwitchMap.java:50)
03-24 17:01:15.836 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:126)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy I/chatty: uid=10147(mobi.pooh3.frpstudy) identical 1 line
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:489)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:484)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:185)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at com.jakewharton.rxbinding2.widget.CompoundButtonCheckedChangeObservable$Listener.onCheckedChanged(CompoundButtonCheckedChangeObservable.java:43)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
03-24 17:01:15.837 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.widget.ToggleButton.setChecked(ToggleButton.java:71)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.widget.CompoundButton.toggle(CompoundButton.java:127)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.widget.CompoundButton.performClick(CompoundButton.java:132)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.view.View$PerformClick.run(View.java:24770)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.os.Looper.loop(Looper.java:164)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-24 17:01:15.838 23926-23926/mobi.pooh3.frpstudy W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Pooh3Mobi** [comment]
```kotlin
        val outputs = sToggledProgress.map{ metronome -> metronome.create(Inputs(
                seekBar.progress.toLong(), // << it can send 0 value to Observable.interval()
                sProgress,
                sToggle
        ))}
```

**Comment by Pooh3Mobi** [comment]
🎉🎉🎉 
https://github.com/Pooh3Mobi/Kotlin-FrpStudy/pull/4
